# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 395673d6ead9a9f9a2f9fa6f51130bf6b76aec8d58b3c2c18658177caf27a976b9178fbe14064ceccf93161e1cbdd54c5ea1afe68774f728dac47c0e59afb622

test:
  secret_key_base: 0a6c9669d23f5a2b5ed7cc8f415399475acf447930953ce93f474c1a437fe143ce33901259323bc2054f9e2d7968f33cae54ce753df6867c5c4aa3ce7dcaa77d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
